### ISSUE TITLE
Idle Master no longer finds cards.

### ISSUE THREAD

**Issue by jtjono** [jshackles/idle_master#103]
First time i used Idle Master it worked like a charm. But I haven't been able to find cards for over a month, it will only say 0 cards to drop and 0 games left to idle. Please help!
http://imgur.com/GKeCFP6

**Comment by Chris92de** [comment]
Do you sort by "mostvalue" or "leastvalue"?
If so, disable the sorting method and it should work.

The error lies with EnhancedSteam's API being non-functional at the moment, e.g. [this results in an error message](http://api.enhancedsteam.com/market_data/average_card_price/?appid=300&cur=usd)

**Comment by jtjono** [comment]
How do i disable the sorting method? I only have this: http://imgur.com/4tyOwVF

**Comment by Zerathos** [comment]
You already have it disabled.

**Comment by jtjono** [comment]
Still says: http://imgur.com/qXx7xqA

**Comment by jshackles** [comment]
Does your badges page indicate that you have games with available card drops?

http://steamcommunity.com/my/badges/

They're not infinite.

**Comment by jtjono** [comment]
Ah! I see yea it says 0 card drops remaining, 0 games with drops remaining. Sorry about that. Do you know why it says that? I haven't had card drops in a month or so.

**Comment by Zerathos** [comment]
You only get so many card drops per game, then you need to either wait for cards to be added to games that didn't have them previously, buy more games with cards in them, or spend money in free to play games with cards.

**Comment by CorruptComputer** [comment]
This can be closed.
