### ISSUE TITLE
"Next check" is stuck at 0:00

### ISSUE THREAD

**Issue by HyphenSam** [jshackles/idle_master#111]
http://i.imgur.com/LUuoLU4.png
This happens after a few hours of use. Restarting Idle Master fixes it, for a while.

**Comment by cardonator** [comment]
I get the same problem.

**Comment by mmnumbp** [comment]
Looks like this was fixed in ddc45d3efc7b258947cba0221aa076b4fc371f41

**Comment by cardonator** [comment]
Indeed it seems to not be happening any longer.

**Comment by HyphenSam** [comment]
I can't seem to replicate this issue, so for now I'll mark it as solved.

**Comment by bendurham441** [comment]
I am still having this problem
