### ISSUE TITLE
Check of Free Games

### ISSUE THREAD

**Issue by Huskynarr** [jshackles/idle_master#114]
Add a Function that checked of the Free Games.
A lot of Free Games have Steam Cards,but they are must first installed, before they are showed on the Badge Page.

**Comment by jshackles** [comment]
Actually, free games on Steam that have trading cards won't drop trading cards until you've made purchases in those games.  1 card = $9 worth of in-game purchases.  See the Trading Card FAQs for more information.

http://steamcommunity.com/tradingcards/faq/
