### ISSUE TITLE
[Bug]Idle_master failed to read badge page

### ISSUE THREAD

**Issue by BlackHobbiT** [jshackles/idle_master#122]
I think, it's linked with SummerSale2015 - new badge with button "play", which leads to http://store.steampowered.com/app/368020/

Here's exception
System.Net.WebException: Удаленный сервер возвратил ошибку: (404) Не найден.
   в System.Net.WebClient.OpenRead(Uri address)
   в System.Net.WebClient.OpenRead(String address)
   в System.Windows.Forms.PictureBox.Load()
   в System.Windows.Forms.PictureBox.Load(String url)
   в IdleMaster.frmMain.startIdle(String appid)
   в IdleMaster.frmMain.<tmrReadyToGo_Tick>d__1e.MoveNext()
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

**Comment by jshackles** [comment]
This can be fixed by adding 368020 to your Idle Master blacklist.  An updated version is being worked on that will correct this issue.

**Comment by BlackHobbiT** [comment]
Yeah, i just think about it :-D
Thanks
