### ISSUE TITLE
Improve idling

### ISSUE THREAD

**Issue by Phyxion** [jshackles/idle_master#124]
As there now seems to be a 2 hour delay, I'd suggest the following:
- Fetch a list of all games with cards.
- Find all games with playtime < 2 hours.and start them all together.
- Wait until all games have a playtime > 2 hours.
- Idle one by one.

**Comment by MiteshNinja** [comment]
Came here to mention this. I'm not expecting it to be very hard to implement, but JShackles is a busy guy :P

**Comment by gricey432** [comment]
+1 for this idea

**Comment by biship** [comment]
Would love this implemented. I understand author is a busy busy man.

**Comment by Mikachu** [comment]
For now, you can manually run steam-idle.exe appid a bunch of times with different appids, and it'll pop up a window for each game it's idling, then quit them all after 2 hours and start idlemaster.exe again. (You can find it in appdata\local\apps\2.0\... somewhere in your user folder). (open a command prompt and drag the exe file onto it, and type a space and the appid).

**Comment by Phyxion** [comment]
@Mikachu That's way too much work.

**Comment by HyphenSam** [comment]
I agree, that's way too much work for an app designed to be convenient.
If I were to do that I might as well use Steam Achievement Manager.

**Comment by Black4Blade** [comment]
Nice idea
Dose it confirm to work?

**Comment by MonkAlex** [comment]
So, check Fork https://github.com/MonkAlex/idle_master pls.
Improved - start all games have a playtime < 2 hours.
Not work - "Wait until all games have a playtime > 2 hours." -- start idle AND all other game. No idea, how it working.

Need test.

**Comment by claell** [comment]
Currently only 30 games idle at a time. Is this wanted / safer?

**Comment by MonkAlex** [comment]
Steam add playtime only for 30-35 game in one time.

**Comment by claell** [comment]
Alright, thanks for explaining.
