### ISSUE TITLE
Source build error... HtmlAgilityPack, Newtonsoft.Json, Steamworks.NET

### ISSUE THREAD

**Issue by Stadtguerilla** [jshackles/idle_master#127]
Hello I have a problem.
I wanted to go to the source. but there are always 3 warnings
I think it be missing 3 FILES HtmlAgilityPack, Newtonsoft.Json, Steamworks.NET

**Comment by jshackles** [comment]
HtmlAgilityPack and Newtonsoft.Json can both be retrieved via the NuGet Package Manager built in to Visual Studio.

Steamworks.NET is available from https://github.com/rlabrecque/Steamworks.NET

**Comment by HoldOffHunger** [comment]
Just a note --

You'll also need System.Windows.Forms and Steamworks appears now to be released as Steamworks.Core.
