### ISSUE TITLE
Hide 'currently in-game' when idling multiple games

### ISSUE THREAD

**Issue by Phyxion** [jshackles/idle_master#139]
Or add a list of games there instead.

**Comment by JHNeveo** [comment]
Or an option to choose between the mode "idle one" and "idle many", because the idle many is good for the first 2h clause, then the idle one is better to drop card (i have the feeling the idle many cannot drop properly, which is the reason i use both the new and old version of idlemaster alternatively)

**Comment by Phyxion** [comment]
After 2 hours the game idles only one game, it doesn't show correctly. Idling multiple games at the same time will not drop cards.

**Comment by JHNeveo** [comment]
An example better than a long explanation : 

I have 260 game to idle, what i do now is : start the last version of idle master and idle 31 at once. and changing the lot each 2h. Then, the day after, i use the old version of idle master to start idle one by one on game with more than 2h.

I'm stopping here, i notice my comment have to be in a different issue thread.

**Comment by MonkAlex** [comment]
Its not simple to change, but i take it. Maybe :) Its small improve idle, but i know, u want show all info about process.

**Comment by Harg2001** [comment]
>Or an option to choose between the mode "idle one" and "idle many", because the idle many is good for the first 2h clause, then the idle one is better to drop card (i have the feeling the idle many cannot drop properly, which is the reason i use both the new and old version of idlemaster alternatively)
 
> An example better than a long explanation :
> I have 260 game to idle, what i do now is : start the last version of idle master and idle 31 at once. and changing the lot each 2h. Then, the day after, i use the old version of idle master to start idle one by one on game with more than 2h.
> I'm stopping here, i notice my comment have to be in a different issue thread.

I just switched account, no worries.

**Comment by Harg2001** [comment]
maybe a clue could be :

in frmMain.cs

What you can change is in the StartIdle method, add something like :

    if(CanIdleBadges.count > 1)
      {lblGameName.Visible = false;}
    else
      {lblGameName.Visible = true;}

**Comment by MonkAlex** [comment]
https://github.com/MonkAlex/idle_master/releases/tag/1.0.1.2

or u want list or idled games with links to steam store?

**Comment by Phyxion** [comment]
Already fixed a long time ago,
