### ISSUE TITLE
Multiple games idling broken

### ISSUE THREAD

**Issue by Phyxion** [jshackles/idle_master#140]
It launches all games left to idle, even those that have already been idling for more than 2 hours. It should only start idling the games that have a play time less than 2 hours. Then, it should idle one game at a time.

**Comment by tekanoma** [comment]
did you download 1.0.1.0, the newest update? that sounds like the error that was fixed

**Comment by Phyxion** [comment]
Yes, it's the latest version, 1.0.1.0. Looking at the code I think it might be just one game (I only had two), the one from 'CurrentBadge'. It shouldn't call StartIdle when it's still idling multiple games.

**Comment by MonkAlex** [comment]
You can click skip button, to change current game and skip idle games with over 2 hour.

Its not critical. Or not?

**Comment by Phyxion** [comment]
Yes but that's manual work, which I'm looking to avoid with an application like this. It's not critical but it adds a lot of additional play time to the game and it shouldn't start it until every game is done with idling for 2 hours. This additional play time is significantly when you restart the idle program (which I do frequently when I buy another game) for another game, it'll add up soon. For one game I now have 8 hours of idling with 0 card drops because I restart it.

**Comment by MonkAlex** [comment]
So, its not critical for me, but i think about it. 
Need add multiple idle mode without crash current work, need more time to write code and test it.
Maybe anyone fix it T_T

**Comment by Harg2001** [comment]
I just have a glance at the code, a clue could be :

in frmMain.cs

There is

    public void UpdateIdleProcesses()
    {
      foreach (var badge in CanIdleBadges.Where(b => !Equals(b, CurrentBadge) && b.HoursPlayed >= 2 && b.InIdle))
        badge.StopIdle();

      foreach (var badge in CanIdleBadges.Where(b => !Equals(b, CurrentBadge) && b.HoursPlayed < 2).Take(30))
        badge.Idle();
    }

    public void StartIdle(Badge badge)
    {
      // Set the currentAppID value
      CurrentBadge = badge;

      // Place user "In game" for card drops
      CurrentBadge.Idle();
      Thread.Sleep(500);

      UpdateIdleProcesses();

What you can change is in the StartIdle method, add something like :

    if(CanIdleBadges.count > 1)
      {UpdateIdleProcesses();}
    else
      {CurrentBadge = badge;CurrentBadge.Idle();/*and maybe other line*/}

This is probably not sufficient. I'm not aware if there is other code impacted.

**Comment by Phyxion** [comment]
It's not sufficient. I already applied several changes to my own fork to fix this. I'm still testing it (haven't reached 0 games left to idle, yet) but it's looking good so far. If it's working I'll create a PR for it.

**Comment by Phyxion** [comment]
https://github.com/jshackles/idle_master/pull/142

**Comment by MonkAlex** [comment]
I am so fixed, but need test it, not simple logic =)

**Comment by Phyxion** [comment]
I already most of it and it's working here.

**Comment by Phyxion** [comment]
Doesn't happen anymore (although there still some issues with this, but not what's reported).
