### ISSUE TITLE
Idle Option : idle one or idle many, card game or non-card game

### ISSUE THREAD

**Issue by JHNeveo** [jshackles/idle_master#141]
-

**Comment by MonkAlex** [comment]
Can you draw a mocap (picture)? Then I add all this.
PS: it will take time, but it is logical.

**Comment by Harg2001** [comment]
> Maybe an option to add in the option menu :

> Idle one : IM choose a game based on the IdlingOrder and start to drop card.
Idle many : IM choose a selection of game based on the IdlingOrder and start to idle for time (by default 2h+)

> (I read that currently, there is an auto mode, which select the "idle many" when he detect game with lesser than 2h timecount, then swap to the normal mode after..)

> Sub option : ability to choose the quantity of game in idle many (more or less than 30)

> Also, display two counter for "games left to idle" -> "games left with <2h" and "games left with >2h".

Just switched account no worries. Moccup coming.

**Comment by Harg2001** [comment]
![idle master settings original](https://cloud.githubusercontent.com/assets/13536568/8928580/a302c626-351f-11e5-93f0-7ba080461251.png)
![idle master settings quantity](https://cloud.githubusercontent.com/assets/13536568/8928583/a30f6ffc-351f-11e5-91d2-dd67aad9e888.png)
![idle master settings quantity option](https://cloud.githubusercontent.com/assets/13536568/8928582/a30f646c-351f-11e5-8123-6839f4062071.png)
![idle master](https://cloud.githubusercontent.com/assets/13536568/8928581/a30c5290-351f-11e5-9aca-98b34e621d8c.png)

**Comment by Harg2001** [comment]
This are only suggestion.

**Comment by Harg2001** [comment]
i just saw another issue title "Run all games that have less than 2h playtime"
Maybe a single checkbox with this label can be ok too. 

I'm definitely not expert in ergonomics/communication and UI.

**Comment by Harg2001** [comment]
Also, as the title above said, i forgot to mention on my moccup about "non-card" game.

**Comment by MonkAlex** [comment]
https://github.com/MonkAlex/idle_master/releases/tag/1.0.1.2
test pls and say, it what u want or not? T_T

**Comment by MonkAlex** [comment]
What about this? Shit? T_T
![2015-08-01 18 33 12](https://cloud.githubusercontent.com/assets/6784764/9022165/d3cfe310-387b-11e5-91d2-f895d9481114.png)

**Comment by Harg2001** [comment]
Awesome!

This view make my brain think, which is bad during summer, but i imagine this with a kind of sortable list (http://symfony.com/legacy/images/book/lists.gif). Apex (one of the tech i use) have a component called "shuttle" (http://1.bp.blogspot.com/_tffIKLFlRlY/R5URqy02jeI/AAAAAAAAC_Q/sVQTbUnl_CY/s400/apex-shuttle-example.png) It's easy to implement, but i don't know if the same component exist with your technology. Maybe it can be usefull to select game to idle, with order and priority.

**Comment by MonkAlex** [comment]
I think it's a bad idea to sort games in this list.

By the way, you can test the upgrade:
https://github.com/MonkAlex/idle_master/releases

Pull request will be after a while.
