### ISSUE TITLE
Idle Master / Steam Guard Conflict

### ISSUE THREAD

**Issue by y9yjRQcg7F** [jshackles/idle_master#148]
When you try to sign in, if you have Steam Guard enabled, the Steam Guard "popup" is broken and doesn't look authentic.  When you try enter the Steam Guard two factor code, it will reject it no matter what.

This issue has started recently.  I've tried it on three different virtual machines (Windows 7, 8.1 and 10).  If you check the Steam forum, you'll see that everyone has been having this issue for the past 20 hours or so.

**Comment by taz97** [comment]
ok, problem windows ??

**Comment by y9yjRQcg7F** [comment]
Recognizes Steam as expected:
![cap1](https://cloud.githubusercontent.com/assets/3108516/9226922/e515af40-40de-11e5-96cd-dc1faf3506d3.png)

Sign-in screen works as expected:
![cap2](https://cloud.githubusercontent.com/assets/3108516/9226921/e5154d2a-40de-11e5-9c35-9be2b56e5922.png)

Steam Guard prompt doesn't look authentic:
![cap3](https://cloud.githubusercontent.com/assets/3108516/9226924/e5197f26-40de-11e5-96c7-772ad53e4c63.png)

Steam Guard will reject code no matter what:
![cap4](https://cloud.githubusercontent.com/assets/3108516/9226923/e5177ec4-40de-11e5-9597-ade571ef5761.png)

**Comment by taz97** [comment]
Well this is also my problem,
What's the solution ?

**Comment by y9yjRQcg7F** [comment]
The solution is examining the code, creating a fix and posting a pull request (i.e. only coding will fix this - be patient).

**Comment by jshackles** [comment]
I'm looking into this issue - thank you for the screenshots.  In the mean time, you can enter your authentication data manually by opening settings and clicking on the "lock" icon, then copying your steamLogin and sessionid cookie data from your browser.

**Comment by taz97** [comment]
OK brother ,
I want to know when will you to repair that?

**Comment by jshackles** [comment]
I'll upload an updated version of Idle Master to the website as soon as a fix has been found.

**Comment by taz97** [comment]
thank you brother ,
I hope that the lifting of today's .. and thank you for your efforts @jshackles

**Comment by taz97** [comment]
My brother asked Other,
When you have uploaded your file comment here beg you I'll wait .. @jshackles

**Comment by y9yjRQcg7F** [comment]
@jshackles I'm going to attempt to enter my authentication data manually as you suggest.  I'll have to do a bit of research, but will post my results when complete.

**Comment by taz97** [comment]
Tell us the result @y9yjRQcg7F

**Comment by y9yjRQcg7F** [comment]
@taz97 

Step 1: Use Firefox and visit steamcommunity.com

Step 2: Log in to your steam account.

Step 3: Right click anywhere on the website and click "View Page Info" on the menu.

Step 4: Click the Security tab.

Step 5: Click the View Cookies button.

Step 6: Here you will find a list of the necessary information.  Click on the necessary Cookie and look for the string of text listed at the bottom, which says Content.

**Comment by y9yjRQcg7F** [comment]
@jshackles I'm able to access Idle Master using the method that you suggested - thanks for the tip.

**Comment by taz97** [comment]
Ok,,

**Comment by taz97** [comment]
Ok ,, !!
Well then?
![untitled](https://cloud.githubusercontent.com/assets/13766847/9228153/d7a47c88-411f-11e5-907d-71c4726a8bb6.png)

**Comment by jshackles** [comment]
So it appears that in yesterday's update to Steam, Valve broke compatibility with IE7.  The Web Browser control that Idle Master uses renders the page in IE7 mode, which is what is causing the issue.  Now that I know the *why*, I can start working on a fix.  Hopefully I'll have one available soon.

**Comment by y9yjRQcg7F** [comment]
@jshackles Thanks so much for your work - this software is a great solution for so many people.

**Comment by taz97** [comment]
My friend,
I've been running the program and I do not know how to bring the card? @y9yjRQcg7F

**Comment by y9yjRQcg7F** [comment]
@taz97 It will have to idle for 2 hours before it will begin to produce any cards.  Just let it sit and run overnight - you'll start to see cards pop up in your inventory.  A watched pot never boils...

**Comment by taz97** [comment]
@jshackles  ! HOY HERE?

**Comment by jshackles** [comment]
Yes, see http://steamcommunity.com/groups/idlemastery#announcements/detail/92674823434327400

**Comment by taz97** [comment]
How long should I wait,
It does not appear to me how much time !!!
Why @jshackles 
![untitled](https://cloud.githubusercontent.com/assets/13766847/9234487/be07e874-4141-11e5-9e2a-eb0ea1af937a.png)

**Comment by jshackles** [comment]
Like I said, please see the announcement and follow the instructions there to download the latest version (v1.2).  That version will fix this error.

**Comment by taz97** [comment]
I did for my friend has no win7 and I see win8

I want to see how much time or the like !!
It is this property only for win7 ???

@jshackles 
![11121018_709937149110472_2134431098_n](https://cloud.githubusercontent.com/assets/13766847/9234588/5fa17e70-4142-11e5-87e6-5037915c7437.jpg)
![untitled](https://cloud.githubusercontent.com/assets/13766847/9234590/60db8786-4142-11e5-876d-d3dbff4534da.png)

**Comment by taz97** [comment]
I just want to know if this is a problem in Windows 8 ????

@jshackles

**Comment by taz97** [comment]
@jshackles  << 
I just want to know if this is a problem in Windows 8 ????
and i have trade ban 2 day ?????????? help me> @y9yjRQcg7F
