### ISSUE TITLE
steam-idle crashing (Win7 Ultimate x64)

### ISSUE THREAD

**Issue by Tr3c3** [jshackles/idle_master#15]
Data obtained from Event Viewer:
"Event 1000, Application Error"
Faulting application name: steam-idle.exe, version: 1.0.0.0, time stamp: 0x53d97352
Faulting module name: KERNELBASE.dll, version: 6.1.7601.18409, time stamp: 0x53159a86
Exception code: 0xe0434352
Fault offset: 0x0000c42d
Faulting process id: 0x94f4
Faulting application start time: 0x01cfb98bfa3dcffe
Faulting application path: C:\PROGRA~1\IDLEMA~1\steam-idle.exe
Faulting module path: C:\Windows\syswow64\KERNELBASE.dll
Report Id: 389ea1fb-257f-11e4-aed9-005056c00008

"Event 1026, .NET Runtime"
Application: steam-idle.exe
Framework Version: v4.0.30319
Description: the process was terminated due to an unhandled exception.
Exception Info: System.Net.WebException
Stack:
   at System.Windows.Forms.PictureBox.Load()
   at System.Windows.Forms.PictureBox.Load(System.String)
   at steam_idle.frmMain..ctor(Int64)
   at steam_idle.Program.Main(System.String[])

**Comment by githubhjs** [comment]
Hi @jshackles , is it possible to add a switch on steam-idle.exe to let it not to load image banner?
Some games are with no banner images at all.

Thanks!
