### ISSUE TITLE
Cannot authenticate with SteamGuard

### ISSUE THREAD

**Issue by wastingoctober** [jshackles/idle_master#154]
I have two Steam accounts and have been using IdleMaster for many months now.

I switched from one Steam account to another yesterday, and I was required to go through SteamGuard (which was odd since I had used the account days earlier). However, SteamGuard will not accept my code. It keeps saying "Whoops! Sorry, but that isn't quite right..." and I receive an email with the same code from Steam. I have tried this with both of my accounts (the first one is now requiring SteamGuard as well), and they are behaving the same way.
![2015-08-22_09-51-05](https://cloud.githubusercontent.com/assets/12704747/9424485/cf13bd22-48b3-11e5-9e64-50c481876f14.png)

Please let me know if there is any additional troubleshooting information I can provide.

**Comment by Zerathos** [comment]
This was fixed [in the latest version of idle Master](http://steamcommunity.com/groups/idlemastery#announcements/detail/92674823434327400). You can re-run the installer to force an update if needed.

**Comment by wastingoctober** [comment]
Thank you for the quick update, and I apologize for the duplicate bug report. I have joined the group now so I won't miss these kind of notifications in the future.
