### ISSUE TITLE
cpu usage

### ISSUE THREAD

**Issue by cpasmoi** [jshackles/idle_master#166]
hello, idlemaster is alway using 0.2% to 0.4% with 10% spikes, it's a hight cpu usage for this small program, it's normal ?

using 955be x4 @3.9ghz

The old idlemaster wasn't using that much cpu

**Comment by notMichael** [comment]
Do you still have this problem (issue is closed)?
It definitely should not be always 0.2%. Are those spikes somehow related to something like if you change idling to next game or anything?
What version of idle master are you using? What version of .NET framework are you using? Try to restart computer and turn off most of applications. And run idlemaster "solo". Does problem persists ?
Do you have this problem with any other application ? 

If you have installed Visual studio you can try to run source code with debugger and see diagnostics. And cpu spikes should be commented what caused them.

Good luck
