### ISSUE TITLE
Doesn't work with Lara Croft The Temple of Osiris

### ISSUE THREAD

**Issue by dimon222** [jshackles/idle_master#168]
App stuck on Lara Croft The Temple of Osiris for days now.
It says 0 hours, and steam client doesn't show that I'm playing it.

No cards ever dropped for it.

**Comment by notMichael** [comment]
I just checked store page (http://store.steampowered.com/app/289690/) and cards are not supported. It probably was in history because I have found some, but most likely not now. If you check your badge page, are there any cards missing ? If not then it is not Idle Master's fault. I am sorry

**Comment by dimon222** [comment]
Hmmm.
But what is [that](https://i.imgur.com/gFeyQGs.png) then.

**Comment by notMichael** [comment]
Yeah I have found it as well. It is probably screenshot from the past and then they removed them. I've never seen that before, but it is probably possible. Maybe due to bad user reviews. On the other hand I have seen games where cards were supported, but I was not mentioned at store page. Easy solution is to check your badge list manualy (Steam client - "Your name" - Badges) and find there that Lara, if it is not there those cards were canceled.

**Comment by dimon222** [comment]
It's there. I made this screenshot. Thats why its strange.

**Comment by notMichael** [comment]
Oh I am sorry I missed your name there. Then you are correct and thank you for reporting this. I will try something but not sure where would be the problem. Also sorry for my doubt.

**Comment by notMichael** [comment]
Just few more questions:
1) Do you have anything in your blacklist? IdleMaster - File - Blacklist
2) Are you logged in as a correct user? IdleMaster - File - Settings - tick -> Show Steam username of signed on user
3) What version of IdleMaster are you using? Help - About

**Comment by dimon222** [comment]
1. I added this game to blacklist after finding this strange behavior with this game. But in general it was empty.
2. I'm using only one steam user, so definitely the same one as I use always.
3. Says 1.3.0.0

It might be something related to Steam integration of this game maybe.

**Comment by dimon222** [comment]
False alarm.
I tried to launch it manually, but it showed me that game is regionally locked.
https://steamdb.info/sub/58377/

Crap.
