### ISSUE TITLE
Updated Turkish language file

### ISSUE THREAD

**Issue by delidolu1genc** [jshackles/idle_master#193]
[code]
<?xml version="1.0" encoding="utf-8"?>
<root>
  
  <xsd:schema xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata" id="root">
    <xsd:import namespace="http://www.w3.org/XML/1998/namespace"/>
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="metadata">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0"/>
              </xsd:sequence>
              <xsd:attribute name="name" use="required" type="xsd:string"/>
              <xsd:attribute name="type" type="xsd:string"/>
              <xsd:attribute name="mimetype" type="xsd:string"/>
              <xsd:attribute ref="xml:space"/>
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="assembly">
            <xsd:complexType>
              <xsd:attribute name="alias" type="xsd:string"/>
              <xsd:attribute name="name" type="xsd:string"/>
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1"/>
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2"/>
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" msdata:Ordinal="1"/>
              <xsd:attribute name="type" type="xsd:string" msdata:Ordinal="3"/>
              <xsd:attribute name="mimetype" type="xsd:string" msdata:Ordinal="4"/>
              <xsd:attribute ref="xml:space"/>
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1"/>
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required"/>
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <data name="about" xml:space="preserve">
    <value>&amp;Hakkında</value>
  </data>
  <data name="badge_didnt_load" xml:space="preserve">
    <value>Rozet sayfası açılamadı, _num_ saniye içinde tekrar denenecek</value>
  </data>
  <data name="blacklist" xml:space="preserve">
    <value>&amp;Kara Liste</value>
  </data>
  <data name="blacklist_current_game" xml:space="preserve">
    <value>&amp;Şu andaki oyunu kara listeye ekle</value>
  </data>
  <data name="card_drops_remaining" xml:space="preserve">
    <value>kart düşürme hakkı kaldı</value>
  </data>
  <data name="currently_ingame" xml:space="preserve">
    <value>Şu an oyunda</value>
  </data>
  <data name="exit" xml:space="preserve">
    <value>&amp;Çıkış</value>
  </data>
  <data name="file" xml:space="preserve">
    <value>&amp;Seçenekler</value>
  </data>
  <data name="game" xml:space="preserve">
    <value>&amp;Oyun</value>
  </data>
  <data name="games_left_to_idle" xml:space="preserve">
    <value>oyun rölanti edilecek</value>
  </data>
  <data name="help" xml:space="preserve">
    <value>&amp;Yardım</value>
  </data>
  <data name="hours" xml:space="preserve">
    <value>Saat</value>
  </data>
  <data name="hrs_on_record" xml:space="preserve">
    <value>saat oynandı</value>
  </data>
  <data name="idle_master_connected" xml:space="preserve">
    <value>İdle Master şu an Steam ile bağlı</value>
  </data>
  <data name="idle_master_notconnected" xml:space="preserve">
    <value>İdle Master şu an Steam ile bağlı değil</value>
  </data>
  <data name="idle_now" xml:space="preserve">
    <value>oyun için rölanti başlatıldı</value>
  </data>
  <data name="idling_complete" xml:space="preserve">
    <value>Rölanti tamamlandı, daha fazla düşürülebilir kart yok</value>
  </data>
  <data name="idling_paused" xml:space="preserve">
    <value>Rölanti duraklatıldı</value>
  </data>
  <data name="loading_next" xml:space="preserve">
    <value>Sonraki oyun açılıyor...</value>
  </data>
  <data name="name" xml:space="preserve">
    <value>İsim</value>
  </data>
  <data name="next_check" xml:space="preserve">
    <value>Sonraki onay</value>
  </data>
  <data name="not_ingame" xml:space="preserve">
    <value>Şu an oyunda değil</value>
  </data>
  <data name="official_group" xml:space="preserve">
    <value>&amp;Resmi Grub</value>
  </data>
  <data name="pause_idling" xml:space="preserve">
    <value>&amp;Rölantiyi duraklat</value>
  </data>
  <data name="please_wait" xml:space="preserve">
    <value>Lütfen bekleyiniz...</value>
  </data>
  <data name="reading_badge_page" xml:space="preserve">
    <value>Rozet sayfası okunuyor</value>
  </data>
  <data name="release_notes" xml:space="preserve">
    <value>&amp;Sürüm notları</value>
  </data>
  <data name="resume_idling" xml:space="preserve">
    <value>&amp;Rölantiyi devam et</value>
  </data>
  <data name="settings" xml:space="preserve">
    <value>&amp;Ayarlar</value>
  </data>
  <data name="signed_in_as" xml:space="preserve">
    <value>Olarak oturumda</value>
  </data>
  <data name="sign_in" xml:space="preserve">
    <value>Oturum Aç</value>
  </data>
  <data name="sign_out" xml:space="preserve">
    <value>Oturumu Kapat</value>
  </data>
  <data name="skip_current_game" xml:space="preserve">
    <value>&amp;Şu andaki oyunu atla</value>
  </data>
  <data name="sorting_results" xml:space="preserve">
    <value>Ayarlarınıza göre sonuçlar sıralanıyor, lütfen bekleyiniz...</value>
  </data>
  <data name="statistics" xml:space="preserve">
    <value>&amp;İstatistikler</value>
  </data>
  <data name="steam_ignored" xml:space="preserve">
    <value>Steam işletici durumu göz ardı edildi</value>
  </data>
  <data name="steam_notrunning" xml:space="preserve">
    <value>Steam şu an çalışmıyor</value>
  </data>
  <data name="steam_running" xml:space="preserve">
    <value>Steam şu an çalışıyor</value>
  </data>
  <data name="update_games_status" xml:space="preserve">
    <value>Oyun durumunu güncelleştir</value>
  </data>
  <data name="accept" xml:space="preserve">
    <value>&amp;Kabul Et</value>
  </data>
  <data name="add" xml:space="preserve">
    <value>&amp;Ekle</value>
  </data>
  <data name="add_game_blacklist" xml:space="preserve">
    <value>Kara Listeye Oyun ekle</value>
  </data>
  <data name="advanced_auth" xml:space="preserve">
    <value>Özetli doğrulama bilgisini görüntüle</value>
  </data>
  <data name="auth_data" xml:space="preserve">
    <value>İdle Master doğrulama bilgisi</value>
  </data>
  <data name="cancel" xml:space="preserve">
    <value>&amp;İptal Et</value>
  </data>
  <data name="cookie_warning" xml:space="preserve">
    <value>Bilgiyi yukarıda görüntüle

[UYARI]
Bu bilgileri kimseyle paylaşmayınız,
aksi halde hırsız tarafından Steam hesabınıza giriş yapılma tehdidi oluşabilir.</value>
  </data>
  <data name="general" xml:space="preserve">
    <value>Genel</value>
  </data>
  <data name="idle_individual" xml:space="preserve">
    <value>Her oyunu ayrı rölanti et</value>
  </data>
  <data name="idle_master_settings" xml:space="preserve">
    <value>İdle Master Ayarlar</value>
  </data>
  <data name="idle_simultaneous" xml:space="preserve">
    <value>Oyunları aynı anda 2 saat rölanti et, sonra ayrı ayrı</value>
  </data>
  <data name="idling_behavior" xml:space="preserve">
    <value>Rölanti davranışı</value>
  </data>
  <data name="idling_order" xml:space="preserve">
    <value>Rölanti sıralaması</value>
  </data>
  <data name="ignore_client_status" xml:space="preserve">
    <value>Steam işletici durumunu yoksay</value>
  </data>
  <data name="interface_language" xml:space="preserve">
    <value>Arabirim Dili</value>
  </data>
  <data name="manage_blacklist" xml:space="preserve">
    <value>İdle Master kara listeyi yönet</value>
  </data>
  <data name="minimize_to_tray" xml:space="preserve">
    <value>İdle Master uygulamasını küçült</value>
  </data>
  <data name="ok" xml:space="preserve">
    <value>&amp;Tamam</value>
  </data>
  <data name="order_default" xml:space="preserve">
    <value>Varsayılan (alfabetik sırayla)</value>
  </data>
  <data name="order_least" xml:space="preserve">
    <value>En az kart sayısı olan oyunlara öncelik ver</value>
  </data>
  <data name="order_most" xml:space="preserve">
    <value>En çok kart sayısı olan oyunlara öncelik ver</value>
  </data>
  <data name="order_value" xml:space="preserve">
    <value>En yüksek kart değeri olan oyunlara öncelik ver</value>
  </data>
  <data name="please_login" xml:space="preserve">
    <value>Lütfen Steam'e giriş yapın</value>
  </data>
  <data name="please_restart" xml:space="preserve">
    <value>Lütfen dil değişikliklerin etkili olabilmesi için uygulamayı yeniden başlatın.</value>
  </data>
  <data name="release_notes_title" xml:space="preserve">
    <value>İdle Master sürüm notları</value>
  </data>
  <data name="save" xml:space="preserve">
    <value>&amp;Kaydet</value>
  </data>
  <data name="saving_info" xml:space="preserve">
    <value>İdle Master bilgilerinizi kaydediyor</value>
  </data>
  <data name="show_username" xml:space="preserve">
    <value>Oturumdaki kullanıcının Steam adını göster</value>
  </data>
  <data name="this_session" xml:space="preserve">
    <value>Bu oturum</value>
  </data>
  <data name="total" xml:space="preserve">
    <value>Toplam</value>
  </data>
  <data name="update" xml:space="preserve">
    <value>&amp;Güncelleştir</value>
  </data>
  <data name="validate_failed" xml:space="preserve">
    <value>Yazdığınız veriler geçerli değil.  Lütfen yeniden deneyin.</value>
  </data>
  <data name="validating" xml:space="preserve">
    <value>Onaylanıyor...</value>
  </data>
  <data name="idle_onethenmany" xml:space="preserve">
    <value>Boştaki oyunlar ayrı ayrı en fazla 2 saat, daha sonra aynı anda</value>
  </data>
</root>
[/code]

**Comment by jshackles** [comment]
Translations should be submitted to translate.steamidlemaster.com otherwise they will be overwritten the next time those files are synced.  Thanks.

**Comment by delidolu1genc** [comment]
Ok
Thanks, on site translations of corrected.
