### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by StealthKill** [jshackles/idle_master#212]
HI, 
I want to use the frmBrowser form in my project to have the login but 
when I copy it in my project my webbrowser has a different behavior.
When the steam page is loaded the text boxes are white instead of blue
and If I enter the security code it says always wrong code.

I'm using windows 10 VS2013  is something wrong with my Webbrowser class?

**Comment by jshackles** [comment]
By default, the Webbrowser control will render using the IE engine in compatibility mode.  A few months ago Valve changed their login page and it no longer works in compatibility mode and works exactly as you describe.

To combat this, Idle Master loads a registry key that tells the webbrowser control not to do this.  You can see this in action here:

https://github.com/jshackles/idle_master/blob/master/Source/IdleMaster/Program.cs#L16

This will cause the control to load using "edge" rendering, which resolves the issue.  I alerted Valve of this for users who legitimately are stuck on older versions of IE, but they don't care / won't fix.  Hope this helps!
