### ISSUE TITLE
Shared Games Need Fixed?

### ISSUE THREAD

**Issue by SubsonicWave** [jshackles/idle_master#230]
Now I know this isn't fully your fault, but I wanna know if Shared games are supposed to show up as well since I have them downloaded, and I can play them plus they have cards. 

If not it kinda sucks that I can't, but the application is great!

**Comment by jshackles** [comment]
Although some games you can play through family sharing do have card drops, only the original purchaser of said game is entitled to them, and if the original purchaser of the game runs Idle Master, it should show up correctly.
