### ISSUE TITLE
Help pls. Idle complete

### ISSUE THREAD

**Issue by montiq** [jshackles/idle_master#249]
Hello.
The problem after launch and log in to the program.

In the lower left writes idle complet
But the list of the games do not have, on account have csgo, cs 16.

Help solve the problem, for even earlier thanks !!!

**Comment by TrAnn3l** [comment]
Idlemaster is only for idling games in order to receive the card drops.
If you want to idle time on your CS-Accounts (which is pretty sad) then you should look at the steam-idle.exe

**Comment by montiq** [comment]
I have found a free game of steam and they have the opportunity loss of cards, or they, too, does not count, since it requires the games that have been purchased (or activating) of the steam store

**Comment by WantedFreak** [comment]
@montiq You need to purchase a DLC in steam store or use the market to buy stuff for the game in order to get drops from free2play games.

**Comment by montiq** [comment]
Thx, # WantedFreak and # TrAnn3l
