### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by cogumm** [jshackles/idle_master#271]
Hope is the last that dies!! \o/

**Comment by GreyAsteroid** [comment]
The python version can be used on Linux https://github.com/jshackles/idle_master_py
Unfortunately this version doesn't have support for Linux.

**Comment by wintry** [comment]
use mono
http://www.mono-project.com/download/

mono ASF.exe

**Comment by YoshimiSakuka** [comment]
Unfortunately, the python version on Linux and every third-party repository versions for Linux both don't work. At least in my region PRC.
I don't know if there's some fix methods. Please reply me about that.
