### ISSUE TITLE
İdling Complete 

### ISSUE THREAD

**Issue by EmirhanOkmen** [jshackles/idle_master#290]
i have 12 cards to drop but idling complete 👎

**Comment by jonas-med-ett-s** [comment]
Have you tried signing out in Idle Master and signing in again, making sure to tick the box "Remember me" in the browser window? 

I have also noticed that updating Steamworks.NET helps. I have created a fork with some updates if you want to try it out: [Idle Master Extended](https://github.com/JonasNilson/idle_master_extended/releases).

**Comment by EmirhanOkmen** [comment]
im tried sign out and sign in again but not worked

**Comment by EmirhanOkmen** [comment]
oh i forget remember me :/ problem solwed
