### ISSUE TITLE
Add new features

### ISSUE THREAD

**Issue by pohuiusemail4741** [jshackles/idle_master#60]
[strike] 1.I want this program installer setup not install at Appdata. [/strike]
2.Add refresh bottom to refresh card drop remaining (force check for who not want to wait 15 minute remaining) 
3.Add previous bottom
4.Show what games want to idle (list:names of games)
5.Can select games want to idle
6.You can delete order
7.Anyone can make order games to idle

Thank,
Next idia and glitch will tell you in next updates

**Comment by Enissay** [comment]
+1 For a "Recheck again" button, which will help a lot instead of relaunching the app...

Also, when the the program ends his work, he then should make an auto check (just in case some games has been added in the mean time)

**Comment by jshackles** [comment]
Most of these have in some fashion been introduced in Idle Master 0.8.  I've added a button to force rechecking the card drop status, and a portable version of the program is now available to download from www.SteamIdleMaster.com that doesn't automatically update.

**Comment by Enissay** [comment]
> I've added a button to force rechecking the card drop status

I see none o.O

http://i.imgur.com/TB2jP8d.png

**Comment by jshackles** [comment]
Where it says "1 card drop remaining" is now clickable.  Clicking it will force the program to recheck the status of your card drops with that game.

**Comment by Enissay** [comment]
Oh, my bad...

So no button to force a full recheck for games newly added ? does it auto re-check (refresh) when it completes (in case games has been added in the meanwhile)?

I don't mean to harass you, I just want to understand :)

Thanks again for this great tool <3
