### ISSUE TITLE
Problem with Sign In-Out

### ISSUE THREAD

**Issue by pohuiusemail4741** [jshackles/idle_master#70]
Yesterday I had logged in my steam account:A, But today I want to Idle account:B so I press Sign out and press Sign In again but it also login to account:A.
I had no way to idle account:B. Please fix it "Sign In - Out bottom"

**Comment by MatheusVellone** [comment]
Hey dude, i had the same problem and i solved it running CCleaner on my PC. It deleted all the cookies so i could enter into a different steam account :D
You can find CClenaer on this link: https://www.piriform.com/ccleaner

**Comment by MatheusVellone** [comment]
But, I think a "Delete Cookies" menu, would make life easier :)

**Comment by pohuiusemail4741** [comment]
Thanks Man!

**Comment by jshackles** [comment]
This should be resolved in the latest release.  In 0.8, the browser form will automatically clear and session and cookie data before navigating to the login page, meaning each time that form loads, you'll be asked to enter your credentials even if you previously saved them.
