### ISSUE TITLE
"Steam is not running" displayed (incorrectly) so it will not start

### ISSUE THREAD

**Issue by SwampThing** [jshackles/idle_master#72]
Installed via 2 different versions and already logged in to steam, also reconnected to steam as normal and also connected to steam via webpage as well. "Idle Master connected to steam" ticked and green. 
For some reason it just cannot see that Steam IS running. 
Any ideas?

**Comment by Zerathos** [comment]
Uninstall Idle Master, right click the installer, select "Run as Administrator." If that's how you did it in the first place...I dunno, [but that's what I saw work for a couple other people](https://www.reddit.com/r/Steam/comments/2qluhp/new_version_of_steam_idle_master_released/cn7m70o?context=1).

**Comment by SwampThing** [comment]
Doh. Thanks dude. All fixed. Bit sheepish I hadn't done that ;)

**Comment by jshackles** [comment]
For the record, this happens when Idle Master and Steam are running as different users in Windows.  If you typically launch Steam as an administrator, you'll need to also launch Idle Master as an administrator.

**Comment by SwampThing** [comment]
Ah, cheers jshackles. I did want to know the why of it.

**Comment by theprogramhacker123** [comment]
This will probably solve your problem as it did solve mine: https://www.youtube.com/watch?v=uIJhzhCkiXQ
