### ISSUE TITLE
Cant login 

### ISSUE THREAD

**Issue by jonkev14** [jshackles/idle_master#80]
I have went to your website (http://www.steamidlemaster.com) and dl your file and when i click it. It says i am currently running steam and when i sign in.it loops right back into the little box again 
Please help me.

**Comment by polppol** [comment]
Same here, Im using windows server 2008 R2
anyway to manually config sessionid just like old version?

**Comment by Sergey0944** [comment]
![default](https://cloud.githubusercontent.com/assets/10473987/5690946/6089b058-98cf-11e4-8733-d87816b3ddac.png) Help please, I even at night included it still does not load what do i do ?(

**Comment by Duckbuster** [comment]
Closing and opening it after you sign in for the first time fixed this for me.

**Comment by jonkev14** [comment]
I cant login. I only have one green check not two. Im using windows 7 and i have .net installed so what should i do?
