### ISSUE TITLE
Title formatting isn't working correctly

### ISSUE THREAD

**Issue by Phyxion** [jshackles/idle_master#83]
![idlemaster_01-12-15_16-44-28](https://cloud.githubusercontent.com/assets/7643972/5705588/b97ee30c-9a7a-11e4-8299-5b64cbcf18b2.png)

Check the image (should be May's, not May\u2019s)...

**Comment by Taedirk** [comment]
![2015-01-24_15-51-15](https://cloud.githubusercontent.com/assets/526029/5889029/a390dc88-a3e1-11e4-9889-0fc942e285d8.png)

The ampersand in "Mount & Blade" is dropped entirely as well.
