### ISSUE TITLE
Stopped Working

### ISSUE THREAD

**Issue by HyphenSam** [jshackles/idle_master#86]
http://i.imgur.com/HHeszRi.png
Before I had problems with this, but after I downloaded the new version it worked perfectly fine, until just 15 minutes ago. After I start up Idle Master, it tells me it's checking games for badges, freezes, and  says steam-idle has stopped working. Twice. And another error message pops up from Microsoft .NET Framework with this error message:

"*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

IdleMaster
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Users/Sam/AppData/Local/Apps/2.0/EKLZZ1O8.JBH/OGQYOYO6.5G2/idle..tion_2608479b42bdf612_0000.0007_e6c8b5d36b0e6138/IdleMaster.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

Steamworks.NET
    Assembly Version: 5.0.0.0
    Win32 Version: 5.0.0
##     CodeBase: file:///C:/Users/Sam/AppData/Local/Apps/2.0/EKLZZ1O8.JBH/OGQYOYO6.5G2/idle..tion_2608479b42bdf612_0000.0007_e6c8b5d36b0e6138/Steamworks.NET.DLL

HtmlAgilityPack
    Assembly Version: 1.4.9.0
    Win32 Version: 1.4.9.0
##     CodeBase: file:///C:/Users/Sam/AppData/Local/Apps/2.0/EKLZZ1O8.JBH/OGQYOYO6.5G2/idle..tion_2608479b42bdf612_0000.0007_e6c8b5d36b0e6138/HtmlAgilityPack.DLL

Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.0.30319.18408 built by: FX451RTMGREL
##     CodeBase: file:///C:/windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box."

Not sure what to do about this. Please help.

**Comment by Still34** [comment]
Can confirm, http://puu.sh/eFLXh/50982ab8eb.png

**Comment by HyphenSam** [comment]
It seems to only occur on certain games. After changing the idling order, it works fine until it reaches the certain games.
