### ISSUE TITLE
Executable flagged by Avira

### ISSUE THREAD

**Issue by m3Lith** [jshackles/idle_master#88]
Hey, just wanted to let you know that recently Avira started to throw a notification that the executable contains a pattern for `HEUR/APC (Cloud)`. I believe it started happening only after the [latest version](http://www.steamidlemaster.com/install/Application%20Files/IdleMaster_0_7_0_12/).
I've submitted the file for their review, so they should mark it as clean in future definition updates.

EDIT: they [confirmed](https://analysis.avira.com/en/status?uniqueid=z9AZpgWw4jB7phUmt1cvz47VXdjMA4V5&incidentid=1812490) it's clean. I'm going to close this after they update their definition database.

**Comment by Parsnip** [comment]
It seems like this is a problem again. I just installed idlemaster again after moving to Win10, and Avira flagged the executable as HEUR/APC (Cloud).

**Comment by m3Lith** [comment]
I'm actually on Win10 for a month now too, but I've decided to not use any third party AV, so the most that I can suggest is to submit the file again: https://analysis.avira.com/en/submit.
