### ISSUE TITLE
[Feature Request] Portable Version

### ISSUE THREAD

**Issue by SourSkittles** [jshackles/idle_master#90]
Would love to see a portable version of the non-cmd version :/ as it stands right now I'd rather use the CMD version over the current version just because it's not portable..

**Comment by goattheminge** [comment]
Microsoft OneClick seriously blows. This guy probably uses it so that he can send us a RAT or something to steal our accounts without us checking the source.

**Comment by m3Lith** [comment]
See https://github.com/jshackles/idle_master/issues/62.

**Comment by jshackles** [comment]
A "portable version" of Idle Master can now be downloaded from www.SteamIdleMaster.com.  It will not automatically update, but it can be placed and run from anywhere you'd like.

**Comment by SourSkittles** [comment]
Portable version doesn't seem to work... when I drag it out of the .zip file it just brings up errors for microsoft .net framework (yes I have everything installed correctly) but if I just open up idlemaster while it's still in the .zip it opens without any errors whats so ever.

**Comment by m3Lith** [comment]
Well duh. You have to extract the whole content of the archive, not just the single executable file.

**Comment by SourSkittles** [comment]
No shit I know this.. I'm saying it does the error crap with everything in a folder

**Comment by m3Lith** [comment]
Well that's interesting then. It works for me right out of the box.
