### ISSUE TITLE
[Feature request] Choosing the installation folder

### ISSUE THREAD

**Issue by xur86x** [jshackles/idle_master#91]
It's very important for me to be able to choose where Idle Master is installed.

**Comment by Tsunamical** [comment]
If it matters that much, just use these:
http://www.steamidlemaster.com/install/Application%20Files/IdleMaster_0_7_0_12/

**Comment by xur86x** [comment]
Thanks :)

**Comment by jshackles** [comment]
A "portable version" of Idle Master can now be downloaded from www.SteamIdleMaster.com.  It will not automatically update, but it can be placed and run from anywhere you'd like.
